server:
  port: 8080
  servlet:
    context-path: /risk-admin

spring:
  datasource:
    druid:
      one:
        type:  com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/gorisk?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        test-on-borrow: true
        max-active: 20
        max-wait: 10000
        initial-size: 5

      two:
        type:  com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://localhost:3306/gorisk?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        test-on-borrow: true
        max-active: 20
        max-wait: 10000
        initial-size: 5